### ISSUE TITLE
Complete the information on the members of the Federal Parliament whom did not complete the full session

### ISSUE THREAD

**Issue by laurensdeb** [Parliament-in-Data/Federal-Parliament-Scraper#1]
Right now a lot of Member objects are not found while parsing votes, this is because some parliament members do not complete the full term. We will have to update the JSON files as to solve this problem.

**Comment by laurensdeb** [comment]
- [x] 55
- [x] 54
- [x] 53
- [x] 52

**Comment by laurensdeb** [comment]
@nielsdos Perhaps we should apply the replaced by concept on session 55 as well, this way the Members class can output these details as well when doing a JSON dump.

**Comment by ndossche** [comment]
Afaik the data on session 55 should be complete as well, but I'll check whether any "replaces" field is missing.

**Comment by laurensdeb** [comment]
Yeah I added some members as well before you got started for session 55, they have a field 'inactive' assigned to them if I recall correctly
