### ISSUE TITLE
[BUG] Webserver is sometimes down, slow or returns an error

### ISSUE THREAD

**Issue by LoganDupont** [Parliament-in-Data/Federal-Parliament-Scraper#48]
**Describe the bug**
It seems that the webserver sometimes goes down or throws an error. If I try a second time to access some json files it seems to work again. So there is no consistancy why the server throws errors, is slow or goes down.

**To Reproduce**
1. Go to a json file ex. https://parlement.thundr.be/sessions/55/meetings/134.json
2. See error ex. 
- Error - Request ID: 01GAYHS5WGTGV2YDYZCKCVCSZ3
-  Error 520 Ray ID: 73de24d7fba7d49c • 2022-08-20 21:15:32 UTC
-  Error 521 Ray ID: 73de24742d64d49c • 2022-08-20 21:15:06 UTC
-  Error 521 Ray ID: 73de24239bb5b9ae • 2022-08-20 21:14:53 UTC
-  Error 521 Ray ID: 73de20b1c9e0d4b4 • 2022-08-20 21:12:32 UTC

**Expected behavior**
We should see the data from the json file

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/6780720/185767002-2d8b7c3f-b910-4d35-bc6d-6555fddd3b06.png)
![afbeelding](https://user-images.githubusercontent.com/6780720/185767049-c3f3c7f2-eed8-4780-a4e4-c2e458394673.png)
![afbeelding](https://user-images.githubusercontent.com/6780720/185767068-f80a3a98-4ed2-4a95-9b51-c2957fdc8e24.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Browser [e.g. Firefox]
 - Version [e.g. 103.0.2]

**Additional context**
/

**Comment by ndossche** [comment]
Thanks for the report.
The server hosting we use is Netlify, which indeed seems to have had some problems yesterday.

From "https://www.netlifystatus.com/":

> From 21:10-21:35 UTC, we saw increased latencies and errors on our Standard Edge Network. The situation was resolved, but our team continues to monitor.

As this problem has been resolved and everything seems to be fine now, I'll close this issue for now :)
