### ISSUE TITLE
[BUG] Scraper didn't scrape plenary meetings 22/09/22

### ISSUE THREAD

**Issue by LoganDupont** [Parliament-in-Data/Federal-Parliament-Scraper#50]
**Describe the bug**
It seems there is again an issue with the scraper. If we go to https://parlement.thundr.be/sessions/55/session.json you will see that the last plenary meeting is `id` 201 with `date` 2022-07-20T00:00:00. Normally there should be a new one with `id` 202 from 22/09/22.

**To Reproduce**
1. Go to https://parlement.thundr.be/sessions/55/session.json
2. Click on `meetings.plenary[0]`
3. You will see the most recent plenary meeting that has been scraped (https://parlement.thundr.be/sessions/55/meetings/201.json)

**Expected behavior**
I would expect to see the most recent plenary meeting that has happened

**Screenshots**
/

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 105.0

**Smartphone (please complete the following information):**
/

**Additional context**
/

**Comment by ndossche** [comment]
https://parlement.thundr.be/sessions/55/meetings/202.json does exist however, so I believe this is Cloudflare caching which did not yet invalidate the cached version of `sessions/55/session.json`.
I'll check back at this later.

**Comment by ndossche** [comment]
The cache has updated, the meeting is reachable from the sessions json now. I'll go ahead and close this issue now.

**Comment by LoganDupont** [comment]
Thank you for looking at it!
